### ISSUE TITLE
Skip setting read-only parameters during model export

### ISSUE THREAD

**Issue by imbur** [viatra/massif#104]
The exporter tries to write read-only variables directly.
 * To reproduce: try exporting the `sldemo_clutch_import.simulink` model.
 * Stacktrace: 
```
!ENTRY org.eclipse.core.jobs 4 2 2018-07-26 09:07:59.376
!MESSAGE An internal error occurred during: "Exporting model sldemo_clutch_import...".
!STACK 0
hu.bme.mit.massif.communication.CommandEvaluationException: Exception occurred while evaluating command!
	at hu.bme.mit.massif.communication.AbstractCommandEvaluator.evaluateCommand(AbstractCommandEvaluator.java:65)
	at hu.bme.mit.massif.communication.AbstractCommandEvaluator.evaluateCommands(AbstractCommandEvaluator.java:264)
	at hu.bme.mit.massif.communication.command.MatlabCommand.execute(MatlabCommand.java:118)
	at hu.bme.mit.massif.simulink.api.Exporter.exportBlocks(Exporter.java:499)
	at hu.bme.mit.massif.simulink.api.Exporter.export(Exporter.java:278)
	at hu.bme.mit.massif.simulink.ui.handlers.ExportModelHandler$1.run(ExportModelHandler.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: com.mathworks.engine.MatlabExecutionException: set_param('sldemo_clutch_import/Friction Model','IsSubsystemVirtual','on');
	at com.mathworks.engine.FutureResult.get(FutureResult.java:64)
	at com.mathworks.engine.MatlabEngine.eval(MatlabEngine.java:349)
	at hu.bme.mit.massif.communication.matlabengine.MatlabEngineAccess.executeEval(MatlabEngineAccess.java:105)
	at hu.bme.mit.massif.communication.AbstractCommandEvaluator.evaluateCommand(AbstractCommandEvaluator.java:60)
	... 6 more
Caused by: com.mathworks.mvm.exec.MvmRuntimeException: SubSystem block parameter 'IsSubsystemVirtual' is read-only
	... 10 more
```

**Comment by imbur** [comment]
After the recent modifications related to #8, the readOnly boolean flag should be used instead of the _READONLY suffix.

**Comment by imbur** [comment]
Additionally, if the mask is off, skip setting mask parameters.
