### ISSUE TITLE
Exporter fails when "State" port is present for a block

### ISSUE THREAD

**Issue by imbur** [viatra/massif#126]
**Behavior**: the `State` port type is only partially supported in Massif at the moment. [Here](https://github.com/viatra/massif/blob/1e069c15c2d0753b1d856049638940f312e1cce4/plugins/hu.bme.mit.massif.simulink.api/src/hu/bme/mit/massif/simulink/api/Importer.java#L1135-L1141) state ports are handled as `OutPort`s by the importer, however, this causes misaddressing ports during export. 

**Steps to reproduce**: take the `sldemo_engine` example, import it, then export it.

**Stacktrace**: 
```
!ENTRY org.eclipse.core.jobs 4 2 2018-08-07 19:47:10.220
!MESSAGE An internal error occurred during: "Exporting model sldemo_engine_export...".
!STACK 0
hu.bme.mit.massif.communication.CommandEvaluationException: Exception occurred while evaluating command!
	at hu.bme.mit.massif.communication.AbstractCommandEvaluator.evaluateCommand(AbstractCommandEvaluator.java:65)
	at hu.bme.mit.massif.communication.matlabengine.MatlabEngineEvaluator.evaluateCommand(MatlabEngineEvaluator.java:41)
	at hu.bme.mit.massif.communication.AbstractCommandEvaluator.evaluateCommands(AbstractCommandEvaluator.java:264)
	at hu.bme.mit.massif.communication.command.MatlabCommand.execute(MatlabCommand.java:99)
	at hu.bme.mit.massif.simulink.api.Exporter.createConnectionFromSingleConnection(Exporter.java:974)
	at hu.bme.mit.massif.simulink.api.Exporter.exportLines(Exporter.java:830)
	at hu.bme.mit.massif.simulink.api.Exporter.exportBlocks(Exporter.java:573)
	at hu.bme.mit.massif.simulink.api.Exporter.subSystemExtraActions(Exporter.java:687)
	at hu.bme.mit.massif.simulink.api.Exporter.exportBlocks(Exporter.java:494)
	at hu.bme.mit.massif.simulink.api.Exporter.export(Exporter.java:282)
	at hu.bme.mit.massif.simulink.ui.handlers.ExportModelHandler$1.run(ExportModelHandler.java:142)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: com.mathworks.engine.MatlabExecutionException: ImporterTmpResult = add_line('sldemo_engine_export/Throttle & Manifold','Intake/2','mass(k+1)/1','AutoRouting','on')
	at com.mathworks.engine.FutureResult.get(FutureResult.java:64)
	at com.mathworks.engine.MatlabEngine.eval(MatlabEngine.java:349)
	at hu.bme.mit.massif.communication.matlabengine.MatlabEngineAccess.executeEval(MatlabEngineAccess.java:48)
	at hu.bme.mit.massif.communication.AbstractCommandEvaluator.evaluateCommand(AbstractCommandEvaluator.java:57)
	... 11 more
Caused by: com.mathworks.mvm.exec.MvmRuntimeException: Invalid Simulink object name: Intake/2
	... 15 more
```

**Comment by imbur** [comment]
Fixed on master in e159b173fe147865fe038a9990ec002b5874e250
