### ISSUE TITLE
Examine Trigger port importing

### ISSUE THREAD

**Issue by imbur** [viatra/massif#14]
Investigate why is importing of Trigger port fails with MatlabControl and why is it seamless with CE.

**Comment by imbur** [comment]
This issue was solved partially by adding an extra check to the code when dealing with trigger ports in commit 5f91cecd9a9bd1d6881a663bba713c94f88b84a2. However the root cause is still unclear, so leaving the ticket open.

**Comment by mayerkr** [comment]
During importing the sldemo_clutch_import.mdl example with importer.traverseAndCreateEMFModel(ImportMode.FLATTENING), a java.lang.NullPointerException is thrown with the following trace: 

```
java.lang.NullPointerException
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateSingleEObject.dynamicGet(EStructuralFeatureImpl.java:2584)
	at hu.bme.mit.massif.simulink.impl.BlockImpl.getTrigger(BlockImpl.java:191)
	at hu.bme.mit.massif.simulink.api.adapter.port.InportAdapter.getPortBlockPortCount(InportAdapter.java:76)
	at hu.bme.mit.massif.simulink.api.adapter.port.InportAdapter.connectToBlock(InportAdapter.java:52)
	at hu.bme.mit.massif.simulink.api.Importer.createAndAddPort(Importer.java:1169)
	at hu.bme.mit.massif.simulink.api.Importer.createPorts(Importer.java:1111)
	at hu.bme.mit.massif.simulink.api.Importer.traverseAndCreateEMFModel(Importer.java:589)
```
The BlockImpl class' getTrigger() method passes a null parameter to EStructuralFeatureImpl's dynamicGet() method's _settings_ parameter. Exception is thrown when settings.dynamicGet(index) is called on null.

**Comment by mayerkr** [comment]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=420208 for circumvention. 

> The null argument seems to be a glaring error, but it is circumvented by installing a SettingDelegateFactory that creates BasicSettingDelegate.Stateless instance which ignores the settings/index arguments.
> 
> The problem arises either through no initialization or late initialization. SettingDelegateFactory registration must occur before the static initialization of the EMF generated classes.

**Comment by mayerkr** [comment]
The solution was to manually register the QueryBasedFeatureSettingDelegateFactory and also include it in the classpath.

Example in Kotlin:
```
EStructuralFeature.Internal.SettingDelegate.Factory.Registry.INSTANCE.put("org.eclipse.viatra.query.querybasedfeature", QueryBasedFeatureSettingDelegateFactory())
```

Additionally, the queries have to be registered as well.
