### ISSUE TITLE
Support MatlabEngine mode in headless Massif running in Matlab

### ISSUE THREAD

**Issue by abelhegedus** [viatra/massif#150]

**Comment by reischlb** [comment]
```Warning: A Java exception occurred trying to load the com/mathworks/engine/MatlabEngine class:
Java exception occurred:
java.lang.ExceptionInInitializerError

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Unknown Source)

	at com.mathworks.jmi.OpaqueJavaInterface.findClass(OpaqueJavaInterface.java:137)

Caused by: java.lang.IllegalStateException: Initializing MATLAB Engine API from MATLAB is not supported.

	at com.mathworks.engine.MatlabEngine.<clinit>(MatlabEngine.java:76)

	... 3 more
 
Undefined variable "com" or class "com.mathworks.engine.MatlabEngine.findMatlabAsync".```
