### ISSUE TITLE
Standalone CLI example fails in Matlab 2019a

### ISSUE THREAD

**Issue by ujhelyiz** [viatra/massif#193]
When trying to execute the latest 0.8.0 snapshot version of the standalone CLI example (https://build.incquerylabs.com/jenkins/job/Massif/job/master/lastSuccessfulBuild/artifact/releng/hu.bme.mit.massif.simulink.cli-package), it failed with the following trace:

```
>> CLI_CreateMassifModel_Example
log4j:WARN No appenders could be found for logger (org.eclipse.viatra.query.runtime.util.ViatraQueryLoggingUtil.org.eclipse.viatra.query.runtime.registry.IQuerySpecificationRegistry).
log4j:WARN Please initialize the log4j system properly.
Creating controller..
Controller created
Creating Local Script Evaluator
Local Script Evaluator Created
Importing model: Example_MATLAB
Starting model import...
Traversing top level blocks
Traversing block Example_MATLAB ...
Exception in thread "Thread-23": java.lang.ClassCastException: hu.bme.mit.massif.communication.datatype.MatlabString cannot be cast to hu.bme.mit.massif.communication.datatype.StructMatlabData
	at hu.bme.mit.massif.communication.datatype.StructMatlabData.asStructMatlabData(StructMatlabData.java:51)
	at hu.bme.mit.massif.communication.datatype.StructMatlabData.getStructMatlabDataData(StructMatlabData.java:55)
	at hu.bme.mit.massif.simulink.api.adapter.block.DefaultBlockAdapter.process(DefaultBlockAdapter.java:56)
	at hu.bme.mit.massif.simulink.api.Importer.createBlockInstance(Importer.java:934)
	at hu.bme.mit.massif.simulink.api.Importer.createBlock(Importer.java:870)
	at hu.bme.mit.massif.simulink.api.Importer.createBlocksFromTopLevel(Importer.java:804)
	at hu.bme.mit.massif.simulink.api.Importer.traverseAndCreateEMFModel(Importer.java:620)
	at hu.bme.mit.massif.simulink.cli.CLIEMFCreator$1.run(CLIEMFCreator.java:65)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by thSoft** [comment]
`massif_functions.m` is missing from the Matlab path. We should discuss how this should be handled.

**Comment by thSoft** [comment]
* #156 
* #198
