### ISSUE TITLE
CLIEMFCreator fails with "System default backend not found"

### ISSUE THREAD

**Issue by thSoft** [viatra/massif#196]
When using Massif 0.8 master, the following exception is thrown during import, e.g. with the CLI example:

```
>> CLI_CreateMassifModel_Example
Creating controller..
Controller created
Creating Local Script Evaluator
Local Script Evaluator Created
Importing model: Example_MATLAB
Starting model import...
Traversing top level blocks
Traversing block Example_MATLAB ...
Block Example_MATLAB is traversed
Traversing block Example_MATLAB ...
Block Example_MATLAB is traversed
Traversing block Example_MATLAB ...
Block Example_MATLAB is traversed
Traversing block Example_MATLAB ...
Block Example_MATLAB is traversed
Traversing block Example_MATLAB ...
Block Example_MATLAB is traversed
Top level blocks traversed
Creating ports...
Ports created
Creating connections...
Exception in thread "Thread-40": java.lang.NullPointerException: System default backend not found
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.eclipse.viatra.query.runtime.api.ViatraQueryEngineOptions.getSystemDefaultBackend(ViatraQueryEngineOptions.java:75)
	at org.eclipse.viatra.query.runtime.api.ViatraQueryEngineOptions.access$4(ViatraQueryEngineOptions.java:71)
	at org.eclipse.viatra.query.runtime.api.ViatraQueryEngineOptions$Builder.getDefaultBackend(ViatraQueryEngineOptions.java:173)
	at org.eclipse.viatra.query.runtime.api.ViatraQueryEngineOptions$Builder.build(ViatraQueryEngineOptions.java:162)
	at org.eclipse.viatra.query.runtime.api.ViatraQueryEngineOptions.getDefault(ViatraQueryEngineOptions.java:105)
	at org.eclipse.viatra.query.runtime.api.ViatraQueryEngineManager.getQueryEngine(ViatraQueryEngineManager.java:86)
	at org.eclipse.viatra.query.runtime.api.ViatraQueryEngine.on(ViatraQueryEngine.java:70)
	at org.eclipse.viatra.addon.querybasedfeatures.runtime.QueryBasedFeatureSettingDelegateFactory.getEngineForNotifier(QueryBasedFeatureSettingDelegateFactory.java:81)
	at org.eclipse.viatra.addon.querybasedfeatures.runtime.QueryBasedFeatureSettingDelegate.initializeSettingDelegateInternal(QueryBasedFeatureSettingDelegate.java:151)
	at org.eclipse.viatra.addon.querybasedfeatures.runtime.QueryBasedFeatureSettingDelegate.get(QueryBasedFeatureSettingDelegate.java:129)
	at org.eclipse.emf.ecore.util.BasicSettingDelegate$Stateless.dynamicGet(BasicSettingDelegate.java:185)
	at hu.bme.mit.massif.simulink.impl.SimulinkElementImpl.getName(SimulinkElementImpl.java:128)
	at hu.bme.mit.massif.simulink.api.Importer.createConnections(Importer.java:1278)
	at hu.bme.mit.massif.simulink.api.Importer.traverseAndCreateEMFModel(Importer.java:626)
	at hu.bme.mit.massif.simulink.cli.CLIEMFCreator$1.run(CLIEMFCreator.java:65)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ujhelyiz** [comment]
Tested - it works as expected. Thanks.
