### ISSUE TITLE
Which Eclipse Version is 0.7 compatible with?

### ISSUE THREAD

**Issue by lanpirot** [viatra/massif#222]
I tried installing all kinds of versions of Eclipse (also Java and Matlab), but somehow this error always crept in, when trying the Command Evaluation Server (the Matlab Control works):

modelExporter.createSimulinkModel('...','...')
Creating controller..
Controller created
Creating Local Script Evaluator
Local Script Evaluator Created
Importing model: ...\massif\massif-cli\Example_MATLAB.slx
Java exception occurred:
java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/IStatus has been compiled by a more recent version of the Java Runtime (class file
version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.mathworks.jmi.CustomURLClassLoader.findClass(ClassLoaderManager.java:760)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at hu.bme.mit.massif.simulink.cli.CLIEMFCreator.createSimulinkModel(CLIEMFCreator.java:58)
	at hu.bme.mit.massif.simulink.cli.CLIEMFCreator.createSimulinkModel(CLIEMFCreator.java:79)

This happens on my system with 
Eclipse: Photon (4.8)
Java: 1.8
Matlab: R2018b
Viatra: 2.0
Massif: 0.7

**Comment by abelhegedus** [comment]
`java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/IStatus has been compiled by a more recent version of the Java Runtime (class file
version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

This is not (directly) a Massif problem, it means you are running an Eclipse Platform with minimum Java 11 requirement (class file version 55.0) over Java 8 (class file version 52.0).

Based on the stacktrace, you are running Matlab CLI version, in Matlab R2018b. See https://www.mathworks.com/help/compiler_sdk/java/configure-your-java-environment.html for checking the Java version found by Matlab.

Did you use the [release versions](https://static.incquerylabs.com/projects/massif/release/0.7.0/) or built a new CLI package from source?
