### ISSUE TITLE
Allow Simulink export and import functionality to be directly used fom MATLAB scripts

### ISSUE THREAD

**Issue by lunkpeter** [viatra/massif#63]
It would be beneficial of the export and import features of MASSIF could be directly utilized via MATLAB scripts, without having to use the Eclipse-based application. In order to do this, the following actions need to be undertaken:

- [x] Move MATLAB command implementations from the commandevaluation.server plugin, to a newly introduced commandevaluation.commands plugin which is independent of any inter-JVM communication.
- [x] Introduce a third ICommandEvaluator implementation that directly calls MATLAB commands.
- [x] Introduce a MASSIF CLI API that can be used from MATLAB scripts.
- [x] Create a jar package of the required MASSIF plugins and other dependencies. This jar file will be added to the running MATLAB instance's classpath, and the CLI API classes will be used as entry points. (similar to the current RMI server script)

Currently, development will be undertaken on the 'viatra-master' branch, however once the code reaches a certain point of maturity, it will be ported to the master branch as well.

**Comment by ujhelyiz** [comment]
Test result: having a script file with two export calls fail with a NPE, most likely because the current version of the importer code runs in a background and does not handle if another request is provided before the first one finishes:

```
Creating connections...
Exception in thread "Thread-43" java.lang.NullPointerException
	at hu.bme.mit.massif.simulink.api.Importer.createConnections(Importer.java:1237)
	at hu.bme.mit.massif.simulink.api.Importer.traverseAndCreateEMFModel(Importer.java:592)
	at hu.bme.mit.massif.simulink.cli.CLIEMFCreator$1.run(CLIEMFCreator.java:58)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-41" java.lang.NullPointerException
	at hu.bme.mit.massif.simulink.api.Importer.createConnections(Importer.java:1237)
	at hu.bme.mit.massif.simulink.api.Importer.traverseAndCreateEMFModel(Importer.java:592)
	at hu.bme.mit.massif.simulink.cli.CLIEMFCreator$1.run(CLIEMFCreator.java:58)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ujhelyiz** [comment]
Two additional comments:

 * Debug mode should be off by default, as it is known to be very slow; and there should be an option to turn it on if necessary.
 * When using the CreateMatlabModel example with a custom path, I noticed that the created slx file was put into the current folder, not the folder selected before. This might be an issue with my setup, so it should be tested by others before any steps are taken to fix this.
