### ISSUE TITLE
Class-cast exception is thrown when trying to export a model.

### ISSUE THREAD

**Issue by lunkpeter** [viatra/massif#78]
A class cast exception is thrown when trying to export a model with a given ID, if there is a matlab (.m) script in the workspace with a file name that equals this given ID. The tool should check for name duplication before trying to export the model and notify the user to resolve the name conflict.

- Stack trace:
```
Exception in thread "Thread-48" java.lang.ClassCastException: hu.bme.mit.massif.communication.datatype.MatlabString cannot be cast to hu.bme.mit.massif.communication.datatype.StructMatlabData
	at hu.bme.mit.massif.communication.datatype.StructMatlabData.asStructMatlabData(StructMatlabData.java:49)
	at hu.bme.mit.massif.communication.datatype.StructMatlabData.getStructMatlabDataData(StructMatlabData.java:53)
	at hu.bme.mit.massif.simulink.api.Exporter.createConnectionFromSingleConnection(Exporter.java:918)
	at hu.bme.mit.massif.simulink.api.Exporter.exportLines(Exporter.java:773)
	at hu.bme.mit.massif.simulink.api.Exporter.exportBlocks(Exporter.java:521)
	at hu.bme.mit.massif.simulink.api.Exporter.export(Exporter.java:274)
	at hu.bme.mit.massif.simulink.cli.CLIMatlabCreator$1.run(CLIMatlabCreator.java:57)
	at java.lang.Thread.run(Thread.java:745)
```
How to reproduce:
 - Use head of viatra-master
 - Create a new simulink model, name it 'TEST'
 - Import the given model to create a .simulink file
 - Create a new script in the Matlab workspace named TEST.m
 - Try to export the model

**Comment by imbur** [comment]
Just out of curiosity: what Matlab version were you using?

**Comment by ujhelyiz** [comment]
We have seen this issue with Matlab 2017b.
