### ISSUE TITLE
Unable to import simulink model

### ISSUE THREAD

**Issue by beatrizsanchez** [viatra/massif#79]
Hi, 

I am not sure what I am doing wrong but I am still unable to import a simulink model, that is, transform it into an EMF model. I believe I have installed all required dependencies in my Eclipse Workstation which has the following configuration:

```
eclipse.buildId=4.7.3.M20180330-0640 (oxygen)
java.version=1.8.0_162
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa
```
I have installed MATLAB R2017b and tried importing and exporting while running and not running.

I have set up the Eclipse properties as follows:
![screen shot 2018-05-14 at 5 02 18 pm](https://user-images.githubusercontent.com/6515216/40009000-b0108026-5798-11e8-94d2-8ac51fbb1d5d.png)

I receive the following error when trying to import simulink files from the toolbox examples, including the one used in the test suite (`sldemo_auto_climate_elec.slx`):
```
"Unhandled event loop exception"
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.NullPointerException
	at hu.bme.mit.massif.communication.matlabcontrol.CommandEvaluatorMCImpl.evaluateCommand(CommandEvaluatorMCImpl.java:77)
	at hu.bme.mit.massif.communication.matlabcontrol.CommandEvaluatorMCImpl.evaluateCommands(CommandEvaluatorMCImpl.java:285)
	at hu.bme.mit.massif.communication.command.MatlabCommand.execute(MatlabCommand.java:118)
	at hu.bme.mit.massif.simulink.importer.ui.handlers.ImportModelHandler.importModel(ImportModelHandler.java:150)
	at hu.bme.mit.massif.simulink.importer.ui.handlers.ImportModelHandler.handleFile(ImportModelHandler.java:124)
	at hu.bme.mit.massif.simulink.importer.ui.handlers.ImportModelHandler.execute(ImportModelHandler.java:71)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 39 more
```
You may find the plugins and features installed in my eclipse in this [file](https://github.com/viatra/massif/files/2001631/Eclipse.txt)
 
Any suggestions will be greatly appreciated. Thanks.

**Comment by abelhegedus** [comment]
Hi,

from the list of plugins, it looks like you are using the 0.5.0 release version of Massif, where the CommandEvaluator connector can only be used on Windows (see #4 and 267ce079ade801b1b552a2850b4d3df1e989654b ).
You can try the [latest CI build](https://github.com/viatra/massif#ci-update-site) of Massif 0.6.0 and if it works, we can create an integration build that has a more stable location.

Cheers

**Comment by beatrizsanchez** [comment]
Hi abelhegedus, 

Thank you for your reply. I've downloaded the latest CI build and installed the local repository in a clean Eclipse installation using oxygen and I am still unable to import the sldemo_auto_climate_elec.slx example.

This is the configuration I have on the preferences:
![screen shot 2018-05-22 at 5 07 46 pm](https://user-images.githubusercontent.com/6515216/40375176-bec69d12-5de2-11e8-8127-7fe689fbb403.png)

And this is the error I am getting on the Error log when I try to do an import, having MATLAB running:
```
Unhandled event loop exception
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.NullPointerException
	at hu.bme.mit.massif.communication.matlabcontrol.CommandEvaluatorMCImpl.evaluateCommand(CommandEvaluatorMCImpl.java:76)
	at hu.bme.mit.massif.communication.matlabcontrol.CommandEvaluatorMCImpl.evaluateCommands(CommandEvaluatorMCImpl.java:284)
	at hu.bme.mit.massif.communication.command.MatlabCommand.execute(MatlabCommand.java:118)
	at hu.bme.mit.massif.simulink.importer.ui.handlers.ImportModelHandler.importModel(ImportModelHandler.java:150)
	at hu.bme.mit.massif.simulink.importer.ui.handlers.ImportModelHandler.handleFile(ImportModelHandler.java:124)
	at hu.bme.mit.massif.simulink.importer.ui.handlers.ImportModelHandler.execute(ImportModelHandler.java:71)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 39 more

eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_162
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_MX
Framework arguments:  -keyring /Users/bea/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/bea/.eclipse_keyring
```
[This](https://github.com/viatra/massif/files/2027508/eclipse.log) is the configuration of my eclipse

Any other ideas?

**Comment by beatrizsanchez** [comment]
Hi again, 
Thanks for the quick reply. For my application purposes I would prefer not to use the server connector. I just tried with the empty path to MATLAB and got the same error.

**Comment by beatrizsanchez** [comment]
I tried to run the import programmatically with this [minimal project](https://github.com/beatrizsanchez/sample.massif) but its hard to debug since massif seems to be very tied to the Eclipse Workbench. With this I mean that the execution throws errors of the kind "some plugins that need to be activated (since `getBundle()` in Plugin Activators return `null`) and also the project requires workbench dependencies like [eclipse.core.runtime](https://mvnrepository.com/artifact/org.eclipse.core/org.eclipse.core.runtime). 

Hopefully the minimal example project helps you debug the Matlab Connector. Notice that the sample project requires the massif dependencies as jars or reference the open massif projects on your workspace, since they are not available as pom dependencies. Let me know if I can be of help.

**Comment by beatrizsanchez** [comment]
I just tried to run the import with **no path to the MATLAB executable** in the preferences and with the MatlabControl Connector. The difference is that this time I am using an eclipse application runtime configuration that is using the massif workspace produced with the oomph configuration. Therefore, I believe that the issues that I previously had were dependency conflicts. 

I would suggest that the [prerequisites documentation](https://github.com/viatra/massif#prerequisites) is a bit more detailed as to which plugins and features are required and with which versions.
