### ISSUE TITLE
Log for model import exception 

### ISSUE THREAD

**Issue by raymerta** [viatra/massif#80]
Hi, 

Is there a way to get the log from the exception happened when a Simulink model is imported without building the plugin from the source? I have working Simulink files and I always get the 'Exception occured while importing model' and my model is created partially. It will help me to pinpoint the problem 

Thank you

**Comment by abelhegedus** [comment]
Did you check the `Error Log` view in Eclipse (Show View -> Other... -> Error Log, under General)? It should give you the stack trace in the details for the entry.

**Comment by raymerta** [comment]
Hi, thank you for your direction. I got 'Undefined function or variable 'library_collector' in the exception message. Does that mean some Simulink components that I have can't be converted to EMF? and if that's the case, is there a way to trace which component is that? 

Here's the full error message I got: 

hu.bme.mit.massif.communication.CommandEvaluationException: Exception occurred while evaluating command!
	at hu.bme.mit.massif.communication.matlabcontrol.CommandEvaluatorMCImpl.evaluateCommand(CommandEvaluatorMCImpl.java:85)
	at hu.bme.mit.massif.communication.matlabcontrol.CommandEvaluatorMCImpl.evaluateCommands(CommandEvaluatorMCImpl.java:285)
	at hu.bme.mit.massif.communication.command.MatlabCommand.execute(MatlabCommand.java:118)
	at hu.bme.mit.massif.simulink.api.Importer.createBlockInstance(Importer.java:952)
	at hu.bme.mit.massif.simulink.api.Importer.createBlock(Importer.java:821)
	at hu.bme.mit.massif.simulink.api.Importer.createBlocksFromSubBlocks(Importer.java:791)
	at hu.bme.mit.massif.simulink.api.Importer.createBlock(Importer.java:837)
	at hu.bme.mit.massif.simulink.api.Importer.createBlocksFromSubBlocks(Importer.java:791)
	at hu.bme.mit.massif.simulink.api.Importer.createBlock(Importer.java:837)
	at hu.bme.mit.massif.simulink.api.Importer.createBlocksFromSubBlocks(Importer.java:791)
	at hu.bme.mit.massif.simulink.api.Importer.createBlock(Importer.java:837)
	at hu.bme.mit.massif.simulink.api.Importer.createBlocksFromSubBlocks(Importer.java:791)
	at hu.bme.mit.massif.simulink.api.Importer.createBlock(Importer.java:837)
	at hu.bme.mit.massif.simulink.api.Importer.createBlocksFromSubBlocks(Importer.java:791)
	at hu.bme.mit.massif.simulink.api.Importer.createBlock(Importer.java:837)
	at hu.bme.mit.massif.simulink.api.Importer.createBlocksFromTopLevel(Importer.java:756)
	at hu.bme.mit.massif.simulink.api.Importer.traverseAndCreateEMFModel(Importer.java:572)
	at hu.bme.mit.massif.simulink.importer.ui.handlers.ImportModelHandler$1.run(ImportModelHandler.java:183)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: matlabcontrol.MatlabInvocationException: Method did not return properly because of an internal MATLAB exception
	at matlabcontrol.MatlabInvocationException$Reason.asException(MatlabInvocationException.java:62)
	at matlabcontrol.JMIWrapper$MatlabThreadProxyImpl.returningFeval(JMIWrapper.java:372)
	at matlabcontrol.JMIWrapper$MatlabThreadProxyImpl.returningEval(JMIWrapper.java:313)
	at matlabcontrol.JMIWrapper$5.call(JMIWrapper.java:146)
	at matlabcontrol.JMIWrapper$5.call(JMIWrapper.java:1)
	at matlabcontrol.JMIWrapper$8.run(JMIWrapper.java:220)
	at com.mathworks.jmi.NativeMatlab.dispatchMTRequests(NativeMatlab.java:410)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(Unknown Source)
	at sun.rmi.transport.StreamRemoteCall.executeCall(Unknown Source)
	at sun.rmi.server.UnicastRef.invoke(Unknown Source)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(Unknown Source)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(Unknown Source)
	at matlabcontrol.$Proxy54.returningEval(Unknown Source)
	at matlabcontrol.RemoteMatlabProxy$5.invoke(RemoteMatlabProxy.java:269)
	at matlabcontrol.RemoteMatlabProxy$5.invoke(RemoteMatlabProxy.java:1)
	at matlabcontrol.RemoteMatlabProxy.invoke(RemoteMatlabProxy.java:179)
	at matlabcontrol.RemoteMatlabProxy.returningEval(RemoteMatlabProxy.java:264)
	at hu.bme.mit.massif.communication.matlabcontrol.CommandEvaluatorMCImpl.evaluateCommand(CommandEvaluatorMCImpl.java:77)
	... 18 more
Caused by: com.mathworks.jmi.MatlabException: Undefined function or variable 'library_collector'.
	at com.mathworks.jmi.NativeMatlab.SendMatlabMessage(Native Method)
	at com.mathworks.jmi.NativeMatlab.sendMatlabMessage(NativeMatlab.java:259)
	at com.mathworks.jmi.MatlabLooper.sendMatlabMessage(MatlabLooper.java:120)
	at com.mathworks.jmi.Matlab.mtFevalConsoleOutput(Matlab.java:1780)
	at matlabcontrol.JMIWrapper$MatlabThreadProxyImpl.returningFeval(JMIWrapper.java:333)
	at matlabcontrol.JMIWrapper$MatlabThreadProxyImpl.returningEval(JMIWrapper.java:313)
	at matlabcontrol.JMIWrapper$5.call(JMIWrapper.java:146)
	at matlabcontrol.JMIWrapper$5.call(JMIWrapper.java:1)
	at matlabcontrol.JMIWrapper$8.run(JMIWrapper.java:220)
	at com.mathworks.jmi.NativeMatlab.dispatchMTRequests(NativeMatlab.java:410)

**Comment by abelhegedus** [comment]
There is a library_collector.m file, that has to be available in Matlab in case you are using additional libraries (see https://github.com/viatra/massif/blob/e322ebed5ae5a4cf32d74bee6aa16ec5408ad15c/plugins/hu.bme.mit.massif.simulink.api/scripts/library_collector.m ) this happens automatically with the Command Evaluation Server connector, but has to be done manually in this case.

**Comment by raymerta** [comment]
Hi, 

I have tried to put the library_collector.m path in Path to Matlab executable in Simulink preference and still get the same error message.  Is this the right place to set the additional libraries?

**Comment by abelhegedus** [comment]
No, the library_collector.m must be accessible by the Matlab instance that you are running (see https://www.mathworks.com/help/matlab/matlab_env/what-is-the-matlab-search-path.html ). The best way to check is to start Matlab and try to run library_collector without modifying anything (since that will be how the Matlab Controller based execution will behave).

The Command Evaluation connector server package includes this script and therefore is accessible once the server is started.

We should probably document this limitation of the Matlab Controller connector a bit more in https://github.com/viatra/massif/wiki/UserGuide#matlabcontrol

**Comment by raymerta** [comment]
Thank you! I tried to run the matlab code and regenerate the model. It works like a charm 

I think it will be great if it's listed in the documentation
