### ISSUE TITLE
Eclipse Installer Error

### ISSUE THREAD

**Issue by beatrizsanchez** [viatra/massif#81]
Hi, 

Trying to install the developer workspace as indicated [here](https://github.com/viatra/massif/wiki/DevelopersGuide). 

Having selected the Eclipse Modeling Tools as base product and added the Massif GitHub project, this is the setup view:
<img width="822" alt="screen shot 2018-05-23 at 9 37 16 pm" src="https://user-images.githubusercontent.com/6515216/40449867-ce62aa32-5ed1-11e8-84d1-b23b5a8bfb83.png">

And this is the error I get:
```
Executing bootstrap tasks
Renamed existing configuration folder to /Applications/Eclipses/applications/massif-dev/Eclipse.app/Contents/Eclipse/configuration.1527107868702
Java(TM) SE Runtime Environment 9.0.1+11
Product org.eclipse.products.epp.package.modeling.oxygen
Workspace /Applications/Eclipses/applications/massif-dev/ws
Project com.github.user.project.massif.master
Project com.github.user.project.massif.mylyn-sonar.master
Bundle org.eclipse.oomph.setup 1.9.0.v20180421-1024, build=3502, branch=a3ffd1307564e51e3c406c3e2744bc282019b050
Bundle org.eclipse.oomph.setup.core 1.9.0.v20180425-0647, build=3502, branch=a3ffd1307564e51e3c406c3e2744bc282019b050
Bundle org.eclipse.oomph.setup.installer 1.9.0.v20180426-1142, build=3502, branch=a3ffd1307564e51e3c406c3e2744bc282019b050
Bundle org.eclipse.oomph.setup.p2 1.9.0.v20180419-0636, build=3502, branch=a3ffd1307564e51e3c406c3e2744bc282019b050
Performing P2 Director (Eclipse Modeling Tools (Oxygen))
Offline = false
Mirrors = true
Resolving 60 requirements from 9 repositories to /Applications/Eclipses/applications/massif-dev/Eclipse.app/Contents/Eclipse
Requirement org.eclipse.mylyn.ide_feature.feature.group
Requirement org.eclipse.mylyn.java_feature.feature.group
Requirement org.eclipse.mylyn.pde_feature.feature.group
Requirement org.eclipse.mylyn.team_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.mylyn.github.feature.feature.group
Requirement org.eclipse.mylyn.builds.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.sonarlint.eclipse.feature.feature.group
Requirement org.sonarlint.eclipse.jdt.feature.feature.group
Requirement epp.package.modeling [4.7.0,4.8.0)
Requirement org.eclipse.platform.feature.group [4.7.0,4.8.0)
Requirement org.eclipse.rcp.feature.group [4.7.0,4.8.0)
Requirement org.eclipse.amalgam.discovery.feature.group
Requirement org.eclipse.e4.core.tools.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.emf.cdo.epp.feature.group
Requirement org.eclipse.emf.compare.diagram.sirius.source.feature.group
Requirement org.eclipse.emf.compare.egit.feature.group
Requirement org.eclipse.emf.compare.ide.ui.source.feature.group
Requirement org.eclipse.emf.compare.source.feature.group
Requirement org.eclipse.emf.ecoretools.design.feature.group
Requirement org.eclipse.emf.ecoretools.explorer.contextual.feature.group
Requirement org.eclipse.emf.ecp.sdk.feature.feature.group
Requirement org.eclipse.emf.emfstore.sdk.feature.feature.group
Requirement org.eclipse.emf.parsley.sdk.feature.group
Requirement org.eclipse.emf.parsley.sdk.source.feature.group
Requirement org.eclipse.emf.query.sdk.feature.group
Requirement org.eclipse.emf.sdk.feature.group
Requirement org.eclipse.emf.transaction.sdk.feature.group
Requirement org.eclipse.emf.validation.sdk.feature.group
Requirement org.eclipse.gef.sdk.feature.group
Requirement org.eclipse.gmf.runtime.sdk.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.context_feature.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.ocl.all.sdk.feature.group
Requirement org.eclipse.pde.feature.group
Requirement org.eclipse.sdk.feature.group
Requirement org.eclipse.uml2.sdk.feature.group
Requirement org.eclipse.xsd.sdk.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.mylyn.feature.group
Requirement org.eclipse.mylyn.tasks.core
Requirement org.eclipse.mylyn.tasks.ui
Requirement org.eclipse.viatra.query.sdk.feature.source.feature.group
Requirement org.eclipse.emf.sdk.feature.group [2.9.0,3.0.0)
Requirement org.eclipse.xtext.redist.feature.group [2.9.0,2.13.0)
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.m2e.logback.feature.feature.group
Requirement fr.obeo.releng.targetplatform-feature.feature.group
Requirement org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.oomph.setup.targlets.feature.group
Repository http://download.eclipse.org/mylyn/releases/latest
Repository http://eclipse.sonarlint.org/
Repository http://download.eclipse.org/technology/epp/packages/oxygen
Repository http://download.eclipse.org/releases/oxygen/201804111000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Repository http://download.eclipse.org/egit/updates
Repository http://download.eclipse.org/viatra/updates/release/
Repository http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
Repository http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/
Adding repository http://download.eclipse.org/mylyn/releases/latest
Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
Adding repository http://mbarbero.github.io/fr.obeo.releng.targetplatform/p2/
Adding repository http://download.eclipse.org/viatra/updates/release/
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/releases/oxygen/201804111000
Adding repository http://eclipse.sonarlint.org/
Adding repository http://download.eclipse.org/egit/updates
Adding repository http://download.eclipse.org/technology/epp/packages/oxygen
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3332)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3260)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3141)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1527107898833
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1527107898833 requires 'org.sonarlint.eclipse.jdt.feature.feature.group 0.0.0' but it could not be found

Took 32 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

**Comment by abelhegedus** [comment]
Two comments:
. I have fixed the Oomph Setup, it seems the SonarLint JDT feature has been merged to the main feature. Please try the install again.
. You (probably unintentionally) added the `Mylyn and Sonar` subproject when you added the Massif project (by checking the checkbox in the project tree, you added the optional subprojects as well)

**Comment by beatrizsanchez** [comment]
Hi, thanks again for the quick reply. I've tried the installation again and seems to be working fine :) I was having a lots of issues trying to resolve the dependencies on my own with eclipse and maven so thanks for providing the oomph configuration.

**Comment by abelhegedus** [comment]
You are welcome! By the way, while not yet documented, but we have a Maven repository for Massif snapshots from the viatra-master branch here: https://build.incquerylabs.com/nexus/repository/massif-snapshots/ (browsing through https://build.incquerylabs.com/nexus/#browse/browse:massif-snapshots )

**Comment by beatrizsanchez** [comment]
I was just checking if I had missed the maven repository... thank you for the info!
